#!/usr/bin/env bash

#export DYALOG=$1
export MAXWS=128M WSPATH=$1/ws

cat <<- EOF | "$1/dyalog" -script | while IFS= read line; do [[ "$line" =~ ^\.|:$ ]] && printf $line || echo "$line"; done
	⎕PW←9999
	2⎕FIX'file://$(dirname "$BASH_SOURCE")/Toi.dyalog'
	{⍵≢⍬:⎕←⍵}'$3'('${@:4}'Toi)'$2'
EOF
